pipeline:
  multi-build:
    image: quay.io/tuannvm/drone-docker-publish:latest
    organization: tuannvm
    pull: true
    privileged: true

  # notify:
  #   image: plugins/slack
  #   webhook: ${SLACK_WEBHOOK}
  #   channel: feed-devops
  #   when:
  #     status: [ success, failure ]