FROM golang:1.8
RUN go get -v \
  bitbucket.org/liamstask/goose/cmd/goose \
  github.com/onsi/ginkgo/ginkgo \
  github.com/modocache/gover \
  github.com/mattn/goveralls \
  github.com/gobuffalo/packr/...
