FROM ruby:2.3.8-slim-jessie

RUN apt-get update -qq && apt-get install -y \
  git \
  build-essential \
  patch \
  ruby-dev \
  zlib1g-dev \
  liblzma-dev \
  libxml2-dev \
  libpq-dev \
  openssl \
  curl
