FROM swipesense/ruby-jemalloc:2.3-jessie-slim

RUN apt-get update -qq && apt-get install -y \
  git \
  build-essential \
  patch \
  ruby-dev \
  zlib1g-dev \
  liblzma-dev \
  libxml2-dev \
  libpq-dev \
  openssl \
  imagemagick \
  wget \
  curl
